// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cppsubart
Rcpp::List cppsubart(arma::mat x_train, arma::mat y_mat, arma::mat x_test, arma::mat x_cut, unsigned int n_tree, unsigned int node_min_size, unsigned int n_mcmc, unsigned int n_burn, arma::mat Sigma_init, arma::vec mu_init, arma::vec sigma_mu, double alpha, double beta, double nu, arma::mat S_0_wish, arma::vec A_j_vec, bool hier_prior_sigma, arma::uvec categorical_indicators, bool fit_test);
RcppExport SEXP _subart2_cppsubart(SEXP x_trainSEXP, SEXP y_matSEXP, SEXP x_testSEXP, SEXP x_cutSEXP, SEXP n_treeSEXP, SEXP node_min_sizeSEXP, SEXP n_mcmcSEXP, SEXP n_burnSEXP, SEXP Sigma_initSEXP, SEXP mu_initSEXP, SEXP sigma_muSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP nuSEXP, SEXP S_0_wishSEXP, SEXP A_j_vecSEXP, SEXP hier_prior_sigmaSEXP, SEXP categorical_indicatorsSEXP, SEXP fit_testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x_train(x_trainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_test(x_testSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_cut(x_cutSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_tree(n_treeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type node_min_size(node_min_sizeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_init(Sigma_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma_mu(sigma_muSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S_0_wish(S_0_wishSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type A_j_vec(A_j_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type hier_prior_sigma(hier_prior_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type categorical_indicators(categorical_indicatorsSEXP);
    Rcpp::traits::input_parameter< bool >::type fit_test(fit_testSEXP);
    rcpp_result_gen = Rcpp::wrap(cppsubart(x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test));
    return rcpp_result_gen;
END_RCPP
}
// cppsubart_missing
Rcpp::List cppsubart_missing(arma::mat x_train, arma::mat y_mat, arma::vec n_missing, arma::vec na_indicators, arma::mat x_test, arma::mat x_cut, unsigned int n_tree, unsigned int node_min_size, unsigned int n_mcmc, unsigned int n_burn, arma::mat Sigma_init, arma::vec mu_init, arma::vec sigma_mu, double alpha, double beta, double nu, arma::mat S_0_wish, arma::vec A_j_vec, bool hier_prior_sigma, arma::uvec categorical_indicators, bool fit_test);
RcppExport SEXP _subart2_cppsubart_missing(SEXP x_trainSEXP, SEXP y_matSEXP, SEXP n_missingSEXP, SEXP na_indicatorsSEXP, SEXP x_testSEXP, SEXP x_cutSEXP, SEXP n_treeSEXP, SEXP node_min_sizeSEXP, SEXP n_mcmcSEXP, SEXP n_burnSEXP, SEXP Sigma_initSEXP, SEXP mu_initSEXP, SEXP sigma_muSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP nuSEXP, SEXP S_0_wishSEXP, SEXP A_j_vecSEXP, SEXP hier_prior_sigmaSEXP, SEXP categorical_indicatorsSEXP, SEXP fit_testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x_train(x_trainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n_missing(n_missingSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type na_indicators(na_indicatorsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_test(x_testSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_cut(x_cutSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_tree(n_treeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type node_min_size(node_min_sizeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_init(Sigma_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma_mu(sigma_muSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S_0_wish(S_0_wishSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type A_j_vec(A_j_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type hier_prior_sigma(hier_prior_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type categorical_indicators(categorical_indicatorsSEXP);
    Rcpp::traits::input_parameter< bool >::type fit_test(fit_testSEXP);
    rcpp_result_gen = Rcpp::wrap(cppsubart_missing(x_train, y_mat, n_missing, na_indicators, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_subart2_cppsubart", (DL_FUNC) &_subart2_cppsubart, 19},
    {"_subart2_cppsubart_missing", (DL_FUNC) &_subart2_cppsubart_missing, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_subart2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
