# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppsubart <- function(x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test) {
    .Call('_subart2_cppsubart', PACKAGE = 'subart2', x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test)
}

cppsubart_2d <- function(x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test) {
    .Call('_subart2_cppsubart_2d', PACKAGE = 'subart2', x_train, y_mat, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test)
}

cppsubart_missing <- function(x_train, y_mat, n_missing, na_indicators, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test) {
    .Call('_subart2_cppsubart_missing', PACKAGE = 'subart2', x_train, y_mat, n_missing, na_indicators, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test)
}

cppsubart_missing_2d <- function(x_train, y_mat, n_missing, na_indicators, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test) {
    .Call('_subart2_cppsubart_missing_2d', PACKAGE = 'subart2', x_train, y_mat, n_missing, na_indicators, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, Sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0_wish, A_j_vec, hier_prior_sigma, categorical_indicators, fit_test)
}

cppsubart_univariate <- function(x_train, y, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0, A_j, hier_prior_sigma, categorical_indicators, fit_test) {
    .Call('_subart2_cppsubart_univariate', PACKAGE = 'subart2', x_train, y, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, sigma_init, mu_init, sigma_mu, alpha, beta, nu, S_0, A_j, hier_prior_sigma, categorical_indicators, fit_test)
}

unnormalize_bart_matrix <- function(Z, a, b) {
    .Call('_subart2_unnormalize_bart_matrix', PACKAGE = 'subart2', Z, a, b)
}

